### ISSUE TITLE
isort ignores native skip configuration

### ISSUE THREAD

**Issue by whyscream** [moccu/pytest-isort#33]
In my django project I've configured isort using a `pyproject.toml` configfile to ignore my migrations files:
```
[tool.isort]
profile = "black"
skip_glob = [
	"*/migrations/*.py"
]
```
If I run isort independently, this works as expected.

However when pytest is started using the pytest-isort plugin, it keeps complaining about the ignored files being incorrectly sorted. I can only silence the pytest-isort plugin when I also configure the `isort_ignore` key in the pytest configuration, which means I have to configure the same thing twice.

Packages used:
pytest==6.2.3
isort==5.8.0
pytest-isort==1.3.0

**Comment by stephrdev** [comment]
The reason here is, that we don't call isort as a commandline tool but instead call the python module directly giving it a file: https://github.com/moccu/pytest-isort/blob/master/pytest_isort.py#L59

I don't know if isort ignores the skip_glob here when it gets a filepath presented.

I'm not sure how to solve this issue here. If we start to support the pyproject syntax, we would have to parse the .editorconfig and others too (see https://pycqa.github.io/isort/docs/configuration/config_files/ for all supported configs).

If you have an idea to solve this, I'm keen on a hint.

**Comment by whyscream** [comment]
When reading the code in https://github.com/PyCQA/isort/blob/07cf92116d1d880aa54f8e664804d9e8ffdfeb2a/isort/api.py#L272-L302, it seems that the default behaviour of isort is to ignore the `skip` configured in global settings (`disregard_skip: bool = True`), but the settings will be applied when setting this flag to `False`. I have no idea whether that actually works, and if `pytest-isort` currently is capable of handling a result that indicates a skip?
